INSERT INTO ROOM(ID, NAME) VALUES(1, 'Room1');
INSERT INTO ROOM(ID, NAME) VALUES(2, 'Room2');

INSERT INTO LIGHT(ID, COLOR, STATUS, ROOM_ID, SATURATION) VALUES (1, '#ffffff', 'OFF', 1, 0);
INSERT INTO LIGHT(ID, COLOR, STATUS, ROOM_ID, SATURATION) VALUES (3, '#fff333', 'OFF', 1, 0);
INSERT INTO LIGHT(ID, COLOR, STATUS, ROOM_ID, SATURATION) VALUES (4, '#fff444', 'OFF', 1, 0);
INSERT INTO LIGHT(ID, COLOR, STATUS, ROOM_ID, SATURATION) VALUES (5, '#fff555', 'OFF', 1, 0);
INSERT INTO LIGHT(ID, COLOR, STATUS, ROOM_ID, SATURATION) VALUES (6, '#fff666', 'OFF', 1, 0);
INSERT INTO LIGHT(ID, COLOR, STATUS, ROOM_ID, SATURATION) VALUES (7, '#f6ffff', 'OFF', 1, 100);
INSERT INTO LIGHT(ID, COLOR, STATUS, ROOM_ID, SATURATION) VALUES (8, '#f33fff', 'OFF', 2, 100);
INSERT INTO LIGHT(ID, COLOR, STATUS, ROOM_ID, SATURATION) VALUES (9, '#f88fff', 'OFF', 2, 100);



