INSERT INTO ROOM(ID, NAME) VALUES(10, 'Room1');
INSERT INTO ROOM(ID, NAME) VALUES(9, 'Room2');

INSERT INTO LIGHT(ID, COLOR, STATUS, ROOM_ID) VALUES (1, '#ffff', 'ON', 10);
INSERT INTO LIGHT(ID, COLOR, STATUS, ROOM_ID) VALUES (2, '#ffff', 'OFF', 10);

